"""initial schema

Revision ID: cf1233a75eda
Revises: 
Create Date: 2026-04-02 14:35:47.916543
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf1233a75eda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metric_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=15), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('scorecard_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('channel_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('non_channel_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('outlier_method', sa.String(length=20), nullable=False),
    sa.Column('iqr_multiplier', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_type', 'start_date')
    )
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name')
    )
    op.create_table('pfp_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('grade_a_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grade_b_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grade_c_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grade_d_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grade_f_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['scorecard_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id')
    )
    op.create_table('productivity_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('state_type', sa.String(length=20), nullable=False),
    sa.Column('is_productive', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['scorecard_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecard_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('include_in_score', sa.Boolean(), nullable=False),
    sa.Column('show_on_scorecard', sa.Boolean(), nullable=False),
    sa.Column('min_threshold', sa.Integer(), nullable=True),
    sa.Column('threshold_basis', sa.String(length=50), nullable=True),
    sa.Column('grade_mode', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['scorecard_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'metric_id')
    )
    op.create_table('supervisors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supervisor_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('dynamic_grade_scales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('scorecard_metric_id', sa.Uuid(), nullable=False),
    sa.Column('mean', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('std_dev', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grade_a', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grade_b', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grade_c', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grade_d', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('agent_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scorecard_metric_id'], ['scorecard_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_period_id'], ['scoring_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scoring_period_id', 'scorecard_metric_id')
    )
    op.create_table('manual_grade_thresholds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scorecard_metric_id', sa.Uuid(), nullable=False),
    sa.Column('grade_a', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grade_b', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grade_c', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grade_d', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['scorecard_metric_id'], ['scorecard_metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scorecard_metric_id')
    )
    op.create_table('agent_period_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('scoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('voice_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chat_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('email_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('voice_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('chat_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('email_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('overall_channel_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('non_channel_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_grade', sa.String(length=1), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('logged_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pfp_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pfp_payout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pfp_max_payout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pfp_money_left', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_period_id'], ['scoring_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['scorecard_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'scoring_period_id')
    )
    op.create_table('performance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('scoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('scorecard_metric_id', sa.Uuid(), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('metric_grade', sa.String(length=1), nullable=True),
    sa.Column('metric_points', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scorecard_metric_id'], ['scorecard_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_period_id'], ['scoring_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'scoring_period_id', 'scorecard_metric_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_records')
    op.drop_table('agent_period_scores')
    op.drop_table('manual_grade_thresholds')
    op.drop_table('dynamic_grade_scales')
    op.drop_table('agents')
    op.drop_table('supervisors')
    op.drop_table('scorecard_metrics')
    op.drop_table('productivity_states')
    op.drop_table('pfp_configs')
    op.drop_table('sites')
    op.drop_table('scoring_periods')
    op.drop_table('scorecard_templates')
    op.drop_table('users')
    op.drop_table('metric_definitions')
    op.drop_table('companies')
    # ### end Alembic commands ###
